### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by Darksoz123** [Iceotaku/DELTA4#32]
Hi, I notice the overlay is overlapping with some background elements and with the collection button.
![overlay issue](https://user-images.githubusercontent.com/31354607/209420904-99fedeac-a7f0-4af0-9734-f6cf4568cb48.png)

I loved the skin, it feels really good.

thank you in advance.

**Comment by Iceotaku** [comment]
Look like you use Default UI Scale Please try Change UI Scale to 0.80x Because this skin has using ui 0.80x to make this skin such in-game ui and more 
![osu_2022-12-25_00-34-40](https://user-images.githubusercontent.com/68460824/209446345-ec06eeea-779b-49be-acf7-ef16c09c0478.jpg)
also you using Latest beta bulid Please Download Lite version to test ver.1.0 before release full version 1.0 because this version has separate to prewiew version 1.0 before release 
Here : https://drive.google.com/file/d/1sxAdVcb6O4-M8t3gvKJuDmokTqSuIX2u/view?usp=share_link

**Comment by Iceotaku** [comment]
Tracking fix #37

**Comment by Iceotaku** [comment]
@Darksoz123 i added 1.00x scale ui complete see #37  
here 
![osu!_GMr2cWKytn](https://user-images.githubusercontent.com/68460824/216439197-9335b4e7-a915-46d9-bc34-1129f3cfb57c.png)
This 1.00x scale has apply with ver. 1.0 all issues about 1.0x scale you can check in #37
